name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurando o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Instalar dependências e rodar testes (opcional)
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      # Fazer build da aplicação NestJS
      - name: Build app
        run: npm run build

      # Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t nestjs-app:latest .

      # Fazer push da imagem para o Docker Hub
      - name: Push Docker image
        run: docker tag nestjs-app:latest ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
